# Generated by Django 4.2.7 on 2026-03-21 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedInProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('li_email', models.TextField()),
                ('li_password', models.TextField()),
                ('llm_provider', models.CharField(choices=[('gemini', 'Gemini'), ('mock', 'Mock')], default='gemini', max_length=20)),
                ('gemini_keys', models.TextField(blank=True)),
                ('min_post_age_minutes', models.PositiveIntegerField(default=30)),
                ('max_post_age_minutes', models.PositiveIntegerField(default=360)),
                ('max_comments_per_round', models.PositiveSmallIntegerField(default=6)),
                ('persona_prompt', models.TextField(default='you are a software engineer, you work in backend but can handle a bit of frontend and devops, aspire to be a solution architect.')),
                ('run_parallel', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=False)),
                ('state_file', models.CharField(blank=True, max_length=255)),
                ('pid', models.IntegerField(blank=True, null=True)),
                ('bot_started_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linkedin_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('tier', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('agency', 'Agency'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('max_profiles', models.IntegerField(default=1)),
                ('max_comments_per_day', models.IntegerField(default=10)),
                ('max_targets', models.IntegerField(default=2)),
                ('max_bot_hours_month', models.IntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['tier', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('bot_minutes_used_this_month', models.PositiveIntegerField(default=0)),
                ('usage_month', models.CharField(default='', max_length=7)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='accounts.plan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urn', models.CharField(max_length=120)),
                ('post_text', models.TextField(blank=True)),
                ('comment', models.TextField()),
                ('post_age_minutes', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_logs', to='accounts.linkedinprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TargetProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedin_url', models.URLField()),
                ('label', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='accounts.linkedinprofile')),
            ],
            options={
                'ordering': ['label', 'linkedin_url'],
                'unique_together': {('owner', 'linkedin_url')},
            },
        ),
    ]
